# Import Dataset

In [24]:
import pandas as pd
import numpy as np

In [25]:
df = pd.read_csv("dataset/UCI_Credit_Card.csv")

df.head(10)

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
0   1    20000.0    2          2         1   24      2      2     -1     -1   
1   2   120000.0    2          2         2   26     -1      2      0      0   
2   3    90000.0    2          2         2   34      0      0      0      0   
3   4    50000.0    2          2         1   37      0      0      0      0   
4   5    50000.0    1          2         1   57     -1      0     -1      0   
5   6    50000.0    1          1         2   37      0      0      0      0   
6   7   500000.0    1          1         2   29      0      0      0      0   
7   8   100000.0    2          2         2   23      0     -1     -1      0   
8   9   140000.0    2          3         1   28      0      0      2      0   
9  10    20000.0    1          3         2   35     -2     -2     -2     -2   

   ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  \
0  ...        0.0        0.0        0.0       0.0     689.0       0.0   
1  ...     3272.0     3455.0     3261.0       0.0    1000.0    1000.0   
2  ...    14331.0    14948.0    15549.0    1518.0    1500.0    1000.0   
3  ...    28314.0    28959.0    29547.0    2000.0    2019.0    1200.0   
4  ...    20940.0    19146.0    19131.0    2000.0   36681.0   10000.0   
5  ...    19394.0    19619.0    20024.0    2500.0    1815.0     657.0   
6  ...   542653.0   483003.0   473944.0   55000.0   40000.0   38000.0   
7  ...      221.0     -159.0      567.0     380.0     601.0       0.0   
8  ...    12211.0    11793.0     3719.0    3329.0       0.0     432.0   
9  ...        0.0    13007.0    13912.0       0.0       0.0       0.0   

   PAY_AMT4  PAY_AMT5  PAY_AMT6  default.payment.next.month  
0       0.0       0.0       0.0                           1  
1    1000.0       0.0    2000.0                           1  
2    1000.0    1000.0    5000.0                           0  
3    1100.0    1069.0    1000.0                           0  
4    9000.0     689.0     679.0                           0  
5    1000.0    1000.0     800.0                           0  
6   20239.0   13750.0   13770.0                           0  
7     581.0    1687.0    1542.0                           0  
8    1000.0    1000.0    1000.0                           0  
9   13007.0    1122.0       0.0                           0  

[10 rows x 25 columns]

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 25 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   ID                          30000 non-null  int64  
 1   LIMIT_BAL                   30000 non-null  float64
 2   SEX                         30000 non-null  int64  
 3   EDUCATION                   30000 non-null  int64  
 4   MARRIAGE                    30000 non-null  int64  
 5   AGE                         30000 non-null  int64  
 6   PAY_0                       30000 non-null  int64  
 7   PAY_2                       30000 non-null  int64  
 8   PAY_3                       30000 non-null  int64  
 9   PAY_4                       30000 non-null  int64  
 10  PAY_5                       30000 non-null  int64  
 11  PAY_6                       30000 non-null  int64  
 12  BILL_AMT1                   30000 non-null  float64
 13  BILL_AMT2                   300

# Selected X & Y

In [38]:
x = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

# Split into Train and Test

In [41]:
from sklearn.model_selection import train_test_split

xTrain, xTest, yTrain, yTest = train_test_split(x, y)

# Logistic Regression

In [44]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr.fit(xTrain, yTrain)

LogisticRegression()

In [45]:
yPred = lr.predict(xTest)

### Accuracy Matrices

In [48]:
from sklearn.metrics import jaccard_score

am = jaccard_score(yTest, yPred)

In [49]:
print("Accuracy Matrics: ", am)

Accuracy Matrics:  0.0


### Confusion Matrix

In [50]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(yTest, yPred)

In [51]:
print("Confusion Matrix:\n", cm)

Confusion Matrix:
 [[5860    0]
 [1640    0]]


### F1 Score

In [52]:
from sklearn.metrics import precision_recall_fscore_support

fscore = precision_recall_fscore_support(yTest, yPred, average="macro")

/home/cskushal18/.local/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [53]:
print("F1 Score: ", fscore)

F1 Score:  (0.39066666666666666, 0.5, 0.43862275449101795, None)


### LogLoss

In [54]:
from sklearn.metrics import log_loss

ll = log_loss(yTest, yPred)

In [55]:
print("Log Loss: ", ll)

Log Loss:  7.55247910502047


# KNN Classifier

In [56]:
from sklearn.neighbors import KNeighborsClassifier
k = 4

neigh = KNeighborsClassifier(n_neighbors=k)
neigh.fit(xTrain, yTrain)

KNeighborsClassifier(n_neighbors=4)

In [57]:
yPred = neigh.predict(xTest)
yPred[0:5]

array([0, 0, 0, 0, 0])

### Accuracy Matrix

In [58]:
am = jaccard_score(yTest, yPred)

print("Accuracy Matrics: ", am)

Accuracy Matrics:  0.09350649350649351


### Confusion Matrix

In [60]:
cm = confusion_matrix(yTest, yPred)

print("Confusion Matrx: \n", cm)

Confusion Matrx: 
 [[5575  285]
 [1460  180]]


### F1 Score

In [61]:
fscore = precision_recall_fscore_support(yTest, yPred, average="macro")

print("F1 Score: ", fscore)

F1 Score:  (0.5897815072104913, 0.5305606426371431, 0.5178488043847669, None)


### Log Loss

In [63]:
ll = log_loss(yTest, yPred)

print("Log Loss: ", ll)

Log Loss:  8.036052359251567


# Decision Tree

In [65]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(criterion="entropy", max_depth = 4)
dt.fit(xTrain,yTrain)

DecisionTreeClassifier(criterion='entropy', max_depth=4)

### Accuracy Matrix

In [66]:
print("Accuracy Matrics: ", jaccard_score(yTest, yPred))

Accuracy Matrics:  0.09350649350649351


### Confusion Matrix

In [67]:
print("Confusion Matrix: \n", confusion_matrix(yTest, yPred))

Confusion Matrix: 
 [[5575  285]
 [1460  180]]


### F1 Score

In [68]:
print("F1 Score: ", precision_recall_fscore_support(yTest, yPred, average="macro"))

F1 Score:  (0.5897815072104913, 0.5305606426371431, 0.5178488043847669, None)


### Log Loss

In [69]:
print("Log loss: ", log_loss(yTest, yPred))

Log loss:  8.036052359251567
